---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
config:
  path:
    list: /api/routerFunction/product
    detail: /api/routerFunction/product/{id}
    save: /api/routerFunction/product
    update: /api/routerFunction/product/{id}
    delete: /api/routerFunction/product/{id}
    upload: /api/routerFunction/product/upload
    upload-id: /api/routerFunction/product/upload/{id}
    photo: src/main/resources/photos/

## Include your configuration to Development Environment